### ISSUE TITLE
after composer update dependency not installed in /vendor/bower

### ISSUE THREAD

**Issue by tomskovkajevs** [Beaten-Sect0r/yii2-flatpickr#1]
after composer update dependency (flatpickr-callendar) not installed in /vendor/bower, but in /vendor/bower-asset
both folders are there in my case (bower and bower-asset).

so line in FlatPickrAsset.php:
public $sourcePath = '@bower/flatpickr-calendar/dist';
throws error. For now works if I change @bower to real path like /var/www/website/vendor/bower-asset

**Comment by Beaten-Sect0r** [comment]
Hi!
Try to add in ./common/config/main.php
```php
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
    ],
```
Show your composer.json

**Comment by tomskovkajevs** [comment]
```
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "fxp/composer-asset-plugin": "^1.3.1",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-jui": "*",
		"setasign/fpdf": "*",
        "bower-asset/jquery-ui": ">=1.11.0",
        "bower-asset/flatpickr-calendar": "*",
        "mpdf/mpdf": "*",
		"kartik-v/yii2-widgets": "*",
        "kartik-v/yii2-dropdown-x": "*",
        "kartik-v/yii2-nav-x": "*",
        "kartik-v/yii2-tabs-x": "*",
        "kartik-v/yii2-mpdf": "*",
        "kartik-v/yii2-export": "*",
        "kartik-v/yii2-grid": "@dev",
		"kartik-v/yii2-widget-select2": "@dev",
        "phpoffice/phpexcel": "^1.8",
        "moonlandsoft/yii2-phpexcel": "*",
        "beaten-sect0r/yii2-flatpickr": "*"
    },
    "require-dev": {
        "codeception/codeception": "*",
        "codeception/specify": "*",
        "codeception/verify": "*",
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800,
	"github-oauth": {
		"github.com": "MY_CODE"
	}
    },
    "extra": {
        "fxp-asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
    "scripts": {
        "post-install-cmd": "php init --env=prod --overwrite=n"
    }
}

```

**Comment by Beaten-Sect0r** [comment]
Change to https://github.com/yiisoft/yii2-app-advanced/blob/master/composer.json#L32
Update the composer & fxp/composer-asset-plugin

**Comment by tomskovkajevs** [comment]
Thanks, that was the problem.

**Comment by eniuz** [comment]
I know this is closed now. if you weren't forcing people to use bower path in FlatpickrAsset then probably there wouldn't be a problem. I like this extension but now I need to figure out if I want to use it and override few things (bower path contains plenty of extensions I use) or just remove it

**Comment by Beaten-Sect0r** [comment]
https://github.com/Beaten-Sect0r/yii2-flatpickr/blob/master/composer.json#L30

**Comment by eniuz** [comment]
what if I told you that for some reasons I can't put this line in? Do you have any other solutions?

**Comment by Beaten-Sect0r** [comment]
What is your path to flatpickr-calendar?

**Comment by eniuz** [comment]
this is how I need it
vendor/bower-asset/flatopickr-calendar/dist
Yii installs it in bower-asset and you are poitnting it to bower

**Comment by Beaten-Sect0r** [comment]
what it writes `<?= Yii::getAlias('@bower') ?>`  ?

**Comment by Beaten-Sect0r** [comment]
Show your composer.json

**Comment by Beaten-Sect0r** [comment]
what it writes `<?= Yii::getAlias('@bower') ?>` ?
Show your composer.json

**Comment by eniuz** [comment]
it's vendor/bower. your extension comes from bower-asset. as per composer.json in the repo: 
 "bower-asset/flatpickr-calendar": "*" so it will default to bower-asset not bower

**Comment by Beaten-Sect0r** [comment]
https://github.com/yiisoft/yii2-bootstrap/blob/master/composer.json#L22 - default
My path /app/vendor/bower/flatpickr-calendar
Send pull requests how do you think it should be.

**Comment by Beaten-Sect0r** [comment]
Solving your problem
https://github.com/yiisoft/yii2-app-advanced/commit/785c933ba31c0827dfdab92363898b461d7d40e3

**Comment by eniuz** [comment]
I found as well that my fxp/composer-asset-plugin was out of date. I consider it fixed as it works for me. Cheers!
