### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by loveorigami** [Beaten-Sect0r/yii2-flatpickr#4]
У flatpickr-a наряду с другими
https://chmln.github.io/flatpickr/plugins/
недавно вышел полезный RangeDate плагин
https://github.com/chmln/flatpickr/issues/584#issuecomment-289295697

Было бы очень удобно добавить поддержку плагинов в виджет.

**Comment by Beaten-Sect0r** [comment]
Спасибо! Попробую добавить.

**Comment by Beaten-Sect0r** [comment]
Плагины подключать можно так:
```php
<?php

use bs\Flatpickr\Widget as Flatpickr;
use yii\web\JsExpression;

?>
<?= $form->field($model, 'published_at')->widget(Flatpickr::className(), [
    'locale' => strtolower(substr(Yii::$app->language, 0, 2)),
    'groupBtnShow' => true,
    'options' => [
        'class' => 'form-control',
    ],
    'clientOptions' => [
        'allowInput' => true,
        'defaultDate' => $model->published_at ? date(DATE_ATOM, $model->published_at) : null,
        'enableTime' => true,
        'time_24hr' => true,
        'mode' => 'range',
        'plugins' => new JsExpression("[new confirmDatePlugin({})]"),
    ],
]) ?>
```
Я так понимаю что к этому в assets стоит добавить только три файла?
./flatpickr-calendar/dist/plugins/confirmDate/confirmDate.js,
./flatpickr-calendar/dist/plugins/confirmDate/confirmDate.css,
./flatpickr-calendar/dist/plugins/weekSelect/weekSelect.js

**Comment by loveorigami** [comment]
Это да, но хотелось бы обойтись без JsExpression. А то пол конфига собирается через array, а остальное - через jsExpression.
Типа такого
```php
<?= $form->field($model, 'published_at')->widget(Flatpickr::className(), [
    'locale' => strtolower(substr(Yii::$app->language, 0, 2)),
    'groupBtnShow' => true,
    'options' => [
        'class' => 'form-control',
    ],
//'plugin' => 'confirmDate', вместо этого вызова
'plugins' => [
     Flatpickr::CONFIRM_DATE =>true,
     //или
    Flatpickr::RANGE =>[
    // options
    ]
]

]) ?>
```

плагины расположены тут
https://github.com/chmln/flatpickr/tree/master/src/plugins

**Comment by Beaten-Sect0r** [comment]
Что если так?
```php
<?= $form->field($model, 'published_at')->widget(Flatpickr::className(), [
    'locale' => strtolower(substr(Yii::$app->language, 0, 2)),
    'plugin' => 'confirmDate',
    'theme' => 'dark',
    'groupBtnShow' => true,
    'options' => [
        'class' => 'form-control',
    ],
    'clientOptions' => [
        'allowInput' => true,
        'defaultDate' => $model->published_at ? date(DATE_ATOM, $model->published_at) : null,
        'enableTime' => true,
        'time_24hr' => true,
        'mode' => 'range',
    ],
]) ?>
```

**Comment by loveorigami** [comment]
возможно, но я предполагал, чтобы была возможность одновременно использовать несколько плагинов. Тот же confirmDate с DateRange -> подтвердить дату для диапазона

**Comment by Beaten-Sect0r** [comment]
Добавил поддержку нескольких плагинов https://github.com/Beaten-Sect0r/yii2-flatpickr/commit/d0de51bd483ec1cbf1ef7d47528d7707d0217fc9

**Comment by loveorigami** [comment]
). Пока не пробовал, т.к. не вижу конфигурации плагина.
https://chmln.github.io/flatpickr/plugins/

Должно быть, как я и писал выше
```php
'plugins' => [
     'confirmDate' => [
           'confirmIcon'=> "<i class='fa fa-check'></i>", // your icon's html, if you wish to override
           'confirmText' => "OK ",
           'showAlways' => false,
           'theme' => "light" // or "dark"
     ],
```
и в виджете регистрируете, предварительно проверив на массив, как (условно):
```php
$options = Json::encode($this->plugins['confirmDatePlugin']);
$plugins[] = "confirmDatePlugin($options)";
```

**Comment by Beaten-Sect0r** [comment]
Хорошо, спасибо, в выходные постараюсь поправить. Напишите pull requests, если есть возможность.

**Comment by Beaten-Sect0r** [comment]
https://github.com/Beaten-Sect0r/yii2-flatpickr/commit/249d6b15dbd9d6b85b65a4aa25e3727f74230ef9
Спасибо!
ещё дополнения есть?

**Comment by loveorigami** [comment]
На вид вроде все хорошо. Как поставлю у себя - отпишусь. Спасибо и Вам.

**Comment by Beaten-Sect0r** [comment]
Ещё не ставили?

**Comment by loveorigami** [comment]
Нет. Где планировал, заказчика датапикер от картика устроил. В новом проекте буду тестить.

**Comment by loveorigami** [comment]
Нужны опции для range плагина
https://chmln.github.io/flatpickr/plugins/#rangeplugin-beta

как у confirmDate
